// FRONTEND-ONLY PREVIEW STUB -- see preview-stub/README.md.
//
// Stands in for the real Wails runtime (frontend/wailsjs/runtime), which is generated by
// `wails dev`/`wails build` -- impossible on a machine without Hikvision's SDK vendored, since
// go-hikvision-sdk is a CGO binding and only windows/linux amd64 are supported.
//
// Only the event surface this frontend actually uses is implemented. EventsEmit is exported so the
// bound-method stub (go/main/App.ts) can push the same events the Go side would.

type Handler = (payload: any) => void;

const listeners = new Map<string, Set<Handler>>();

export function EventsOn(eventName: string, callback: Handler): () => void {
  let set = listeners.get(eventName);
  if (!set) {
    set = new Set();
    listeners.set(eventName, set);
  }
  set.add(callback);
  return () => {
    set!.delete(callback);
  };
}

export function EventsEmit(eventName: string, ...data: any[]): void {
  // Copied before iterating: a handler that unsubscribes itself (the stream:stopped path does)
  // would otherwise mutate the set mid-iteration.
  [...(listeners.get(eventName) ?? [])].forEach((cb) => cb(data[0]));
}

export function EventsOff(eventName: string): void {
  listeners.delete(eventName);
}
